[package]
name = "hershell"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1.5.0"
pin-project = "1.1.4"
futures = "0.3.30"
